version: '3.8'
services:
 consum-elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
   environment:
     - discovery.type=single-node
   ports:
     - 9200:9200
 consum-unomi:
   # Unomi version can be updated based on your needs
   image: apache/unomi:1.5.7
   environment:
     - UNOMI_SECURE_HTTP_PORT=9444
     - UNOMI_ELASTICSEARCH_ADDRESSES=consum-elasticsearch:9200
     - UNOMI_THIRDPARTY_PROVIDER1_IPADDRESSES=0.0.0.0/0,::1,127.0.0.1
   ports:
     - 8181:8181
     - 9444:9444
     - 8102:8102
   links:
     - consum-elasticsearch
   depends_on:
     - consum-elasticsearch
